### ISSUE TITLE
times() causes a crash due to incorrect implementation of STUB()

### ISSUE THREAD

**Issue by mato** [rumpkernel/rumprun#4] opened 2015-03-12 11:42 UTC
Any call to the `times()` system call will cause a crash (division by zero). The root cause is due to:
* `times()` calls `getrusage()`
* `getrusage()` is a `STUB()`
* `STUB()` is defined as returning `ENOTSUP` rather than `-1`.

The correct behaviour for STUB should be to return `-1`, however this may cause applications to stop working due to calls returning errors. More discussion is needed, and/or different definitions of stubs.

**Comment by anttikantee** [comment] 2015-04-28 07:08
The real root cause is that sysconf(_SC_CLK_TCK) returned 0 for rump kernels until very recent upstream NetBSD sources.

So, the /-by-0 part will be fixed when the latest sources a pulled up to src-netbsd.  There's also a fictional getrusage() in rumprun now.

I think if there are other problems, they can be deal with in another issue.

**Comment by anttikantee** [comment] 2015-05-27 00:05
Calling times() no longer causes a crash.

**Closed by anttikantee** 2015-05-27 00:05 UTC
Labels: bug
